FROM ubuntu:16.04

ENV LC_ALL=C.UTF-8 LANG=C.UTF-8

RUN dpkg --add-architecture i386 && \
    apt-get update -q && \
    apt-get install -qy \
        wget=1.17.1-1ubuntu1.5 \
        gnupg2=2.1.11-6ubuntu2.1 \
        dirmngr=2.1.11-6ubuntu2.1 \
        python3-software-properties=0.96.20 \
        software-properties-common=0.96.20

RUN apt-get update -q && \
        apt-get install -qy \
        git=1:2.7.4-0ubuntu1.6 \
        p7zip-full=9.20.1~dfsg.1-4.2ubuntu0.1 \
        make=4.1-6 \
        mingw-w64=4.0.4-2 \
        autotools-dev=20150820.1 \
        autoconf=2.69-9 \
        libtool=2.4.6-0.1 \
        gettext=0.19.7-2ubuntu3.1

RUN wget -nc http://dl.winehq.org/wine-builds/Release.key && \
        echo "c51bcb8cc4a12abfbd7c7660eaf90f49674d15e222c262f27e6c96429111b822 Release.key" | sha256sum -c - && \
        apt-key add Release.key && \
    wget -nc http://dl.winehq.org/wine-builds/winehq.key && \
        echo "78b185fabdb323971d13bd329fefc8038e08559aa51c4996de18db0639a51df6 winehq.key" | sha256sum -c - && \
        apt-key add winehq.key && \
    apt-add-repository http://dl.winehq.org/wine-builds/ubuntu/ && \
    apt-get update -q && \
    apt-get install -qy \
        wine-stable-amd64:amd64=4.0~xenial \
        wine-stable-i386:i386=4.0~xenial \
        wine-stable:amd64=4.0~xenial \
        winehq-stable:amd64=4.0~xenial

RUN rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean
